### ISSUE TITLE
handling of "int64" types could be better

### ISSUE THREAD

**Issue by jclulow** [fewensa/fantasy#1]
You note in a few places that the underlying library encodes some subset of `int64` values as a string instead of an integer -- presumably to avoid precision loss when parsing with `JSON.parse()` in Javascript.  There is a crate, [serde-aux](https://crates.io/crates/serde-aux), which includes a routine that can be used with serde deserialisation, [deserialize_number_from_string](https://docs.rs/serde-aux/0.6.1/serde_aux/field_attributes/fn.deserialize_number_from_string.html).  This routine will convert _either_ a string _or_ a number into an appropriate numeric type, in this case `i64`.

I have a rough example of a change to use this, here: https://github.com/jclulow/fantasy/commit/e2c130c7220036d44e81020d3d9bde283777a4ee

This change results in the following change to the generated code: https://github.com/jclulow/rtdlib/commit/108f525cbc3ac96aa9a0b3ba324235d62d763c3c

(Note the rtdlib change also adds `serde-aux` to `Cargo.toml`)

Is something you'd accept as a pull request?  Thanks.

**Comment by fewensa** [comment]
@jclulow Thank you for solving this problem, I think your idea is better (although I don't like to add a lot of dependencies), can you create a pull request? and just now I change code to support td 1.6.x, so maybe have some conflict. If not have an problem, I will update all version of rtdlib.

**Comment by fewensa** [comment]
I want to keep the filter configuration, because not all i64 types will have this problem. just use serde-aux where needed.

**Comment by fewensa** [comment]
Hi @jclulow , Since you did not submit, I changed code with your solution to fix this question.
